// Maps Material Symbols Outlined icon names (used in HTML prototypes)
// to react-native-vector-icons MaterialCommunityIcons equivalents

const iconMap: Record<string, string> = {
  home: 'home',
  group: 'account-group',
  medication: 'pill',
  smart_toy: 'robot',
  person: 'account',
  notifications: 'bell',
  notifications_active: 'bell-ring',
  pill: 'pill',
  calendar_today: 'calendar-today',
  calendar_month: 'calendar-month',
  description: 'file-document-outline',
  format_list_numbered: 'format-list-numbered',
  schedule: 'clock-outline',
  location_on: 'map-marker',
  search: 'magnify',
  add: 'plus',
  remove: 'minus',
  add_circle: 'plus-circle',
  arrow_back: 'arrow-left',
  arrow_forward: 'arrow-right',
  chevron_right: 'chevron-right',
  expand_more: 'chevron-down',
  check: 'check',
  check_circle: 'check-circle',
  delete: 'delete',
  warning: 'alert',
  favorite: 'heart',
  mic: 'microphone',
  send: 'send',
  close: 'close',
  camera: 'camera',
  photo_camera: 'camera',
  photo_library: 'image-multiple',
  image: 'image',
  inventory_2: 'package-variant',
  event_busy: 'calendar-remove',
  vaccines: 'needle',
  syringe: 'needle',
  medical_services: 'medical-bag',
  local_hospital: 'hospital-building',
  lock: 'lock',
  mail: 'email',
  visibility: 'eye',
  visibility_off: 'eye-off',
  settings: 'cog',
  more_vert: 'dots-vertical',
  volume_up: 'volume-high',
  trending_up: 'trending-up',
  history: 'history',
  nest_eco_leaf: 'leaf',
  child_care: 'baby-face-outline',
  event_note: 'calendar-text',
  auto_awesome: 'star-four-points',
  hourglass_empty: 'timer-sand-empty',
  thermometer: 'thermometer',
  steps: 'shoe-print',
  cloud_done: 'cloud-check',
  home_storage: 'archive',
  alarm: 'alarm',
  event_repeat: 'calendar-sync',
  save: 'content-save',
  event_available: 'calendar-check',
  star: 'star',
  edit: 'pencil',
  qr_code: 'qrcode',
  share: 'share-variant',
  info: 'information',
  person_add: 'account-plus',
  wc: 'human-male-female',
  bloodtype: 'water',
  history_edu: 'history',
  verified: 'check-decagram',
  call: 'phone',
  family_restroom: 'human-male-female-child',
  water_drop: 'water',
  healing: 'bandage',
  monitor_heart: 'heart-pulse',
  emergency: 'alert-circle',
  light_mode: 'weather-sunny',
  bedtime: 'weather-night',
  sunny: 'white-balance-sunny',
  language: 'translate',
  security: 'shield-check',
  help_center: 'lifebuoy',
  bug_report: 'bug',
  logout: 'logout',
  phone: 'phone',
  cake: 'cake-variant',
  height: 'human-male-height',
  scale: 'scale-bathroom',
  insert_chart: 'chart-line',
  bar_chart: 'chart-bar',
  access_time: 'clock-time-four-outline',
  document_scanner: 'file-document-outline',
  monitor_weight: 'scale-bathroom',
  show_chart: 'chart-line',
  notification_important: 'bell-alert',
  password: 'lock-reset',
  lock_outline: 'lock-outline',
  pin: 'numeric',
};

export function getIconName(materialSymbolName: string): string {
  return iconMap[materialSymbolName] ?? 'help-circle-outline';
}

export default iconMap;
