export const colors = {
  primary: '#00629d',
  primaryContainer: '#42a5f5',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#00395e',
  primaryFixed: '#cfe5ff',
  primaryFixedDim: '#99cbff',
  onPrimaryFixed: '#001d34',
  onPrimaryFixedVariant: '#004a78',

  secondary: '#526069',
  secondaryContainer: '#d3e2ed',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#56656e',
  secondaryFixed: '#d6e5ef',
  secondaryFixedDim: '#bac9d3',
  onSecondaryFixed: '#0f1d25',
  onSecondaryFixedVariant: '#3b4951',

  tertiary: '#005faf',
  tertiaryContainer: '#57a1ff',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#003769',
  tertiaryFixed: '#d4e3ff',
  tertiaryFixedDim: '#a5c8ff',
  onTertiaryFixed: '#001c3a',
  onTertiaryFixedVariant: '#004786',

  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onError: '#ffffff',
  onErrorContainer: '#93000a',

  background: '#f7fafe',
  onBackground: '#181c1f',
  surface: '#f7fafe',
  onSurface: '#181c1f',
  onSurfaceVariant: '#404751',
  surfaceVariant: '#e0e3e7',
  surfaceContainer: '#ebeef2',
  surfaceContainerLow: '#f1f4f8',
  surfaceContainerHigh: '#e5e8ec',
  surfaceContainerHighest: '#e0e3e7',
  surfaceContainerLowest: '#ffffff',
  surfaceDim: '#d7dade',
  surfaceBright: '#f7fafe',
  surfaceTint: '#00629d',

  outline: '#707882',
  outlineVariant: '#bfc7d3',
  inverseSurface: '#2d3134',
  inverseOnSurface: '#eef1f5',
  inversePrimary: '#99cbff',
} as const;

export type ColorToken = keyof typeof colors;
